export const FETCH_ALL_JOURNALS = 'FETCH_ALL_JOURNALS';
export const FILTER_JOURNALS_BY_NAME = 'FILTER_JOURNALS_BY_NAME';
export const FILTER_JOURNALS_BY_TOPIC = 'FILTER_JOURNALS_BY_TOPIC';
export const SEARCH_JOURNALS_BY_NAME = 'SEARCH_JOURNALS_BY_NAME';
export const DISPLAY_JOURNALS = 'DISPLAY_JOURNALS';